.TH "src/Storage Directory Reference" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Storage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClimateStorage\&.c\fP"
.br
.ti -1c
.RI "file \fBClimateStorage\&.h\fP"
.br
.ti -1c
.RI "file \fBLandmassStorage\&.c\fP"
.br
.ti -1c
.RI "file \fBLandmassStorage\&.h\fP"
.br
.ti -1c
.RI "file \fBTerrainStorage\&.c\fP"
.br
.ti -1c
.RI "file \fBTerrainStorage\&.h\fP"
.br
.in -1c
