.TH "ColorMap" 3 "Wed Jan 16 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorMap \- Struct to hold RGB values for use with QDBMP library\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Draw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBR\fP"
.br
.ti -1c
.RI "char \fBG\fP"
.br
.ti -1c
.RI "char \fBB\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct to hold RGB values for use with QDBMP library\&. 
.PP
Definition at line 8 of file Draw\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char ColorMap::B"

.PP
Definition at line 12 of file Draw\&.h\&.
.SS "char ColorMap::G"

.PP
Definition at line 11 of file Draw\&.h\&.
.SS "char ColorMap::R"

.PP
Definition at line 10 of file Draw\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
