.TH "Compare" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Compare \- Internal class for ordering Point by Perlin noise value\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompare\fP (const bool &revparam=false, int x=0, int y=0, \fBPerlin\fP *perlin=NULL)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (\fBPoint\fP &lhs, \fBPoint\fP &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal class for ordering Point by Perlin noise value\&. 

Internal class to sort Point based on Perlin noise value of x, y coordinate Class for comparing Points for ordering in a priority_queue\&. This is used in Method GridPerlin\&. 
.PP
Definition at line 22 of file GridMapGenerator\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Compare::Compare (const bool & revparam = \fCfalse\fP, int x = \fC0\fP, int y = \fC0\fP, \fBPerlin\fP * perlin = \fCNULL\fP)\fC [inline]\fP"

.PP
Definition at line 28 of file GridMapGenerator\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Compare::operator() (\fBPoint\fP & lhs, \fBPoint\fP & rhs)\fC [inline]\fP"

.PP
Definition at line 41 of file GridMapGenerator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
