.TH "src/utils/Distribution.h" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/Distribution.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWorldArchitect::Distribution\fP"
.br
.RI "This is a utility class for representing normal Gaussian distributions\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBWorldArchitect\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
