.TH "src/Graphics/Draw.c" 3 "Wed Jan 16 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Graphics/Draw.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Draw\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdrawPointsVector\fP (Vector v, BMP *bmp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void drawPointsVector (Vector v, BMP * bmp)"
This function currently does nothing\&. may be used later\&. Was from original tests with qdbmp library\&. 
.PP
Definition at line 7 of file Draw\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
