.TH "src/MapGen/GridMapGenerator.c" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MapGen/GridMapGenerator.c
.SH SYNOPSIS
.br
.PP
\fC#include 'GridMapGenerator\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompare\fP"
.br
.RI "Internal class for ordering Point by Perlin noise value\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
