.TH "src/MapGenSystem/GridMapGenerator.h" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MapGenSystem/GridMapGenerator.h
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <shared_mutex>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <random>\fP
.br
\fC#include 'vector\&.h'\fP
.br
\fC#include 'MapGenerator\&.h'\fP
.br
\fC#include 'GridMap\&.h'\fP
.br
\fC#include 'utils/Perlin\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWorldArchitect::GridMapGenerator\fP"
.br
.RI "This class extends \fBMapGenerator\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBWorldArchitect\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
