.TH "src/utils/GridPoint.h" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/GridPoint.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBWorldArchitect::GridPoint\fP"
.br
.RI "This struct is how a \fBGridMap\fP stores its data for each point internally\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBWorldArchitect\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINVALID_POINT\fP   \-5"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INVALID_POINT   \-5"

.PP
Definition at line 3 of file GridPoint\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
