.TH "src/MapGenSystem/GridMap.h" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MapGenSystem/GridMap.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Map\&.h'\fP
.br
\fC#include 'utils/GridPoint\&.h'\fP
.br
\fC#include 'utils/Logging\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <shared_mutex>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'vector\&.h'\fP
.br
\fC#include 'utils/Distribution\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWorldArchitect::GridMap\fP"
.br
.RI "This class extends \fBMap\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBWorldArchitect\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
