.TH "src/utils/Logging.cpp" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/Logging.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Logging\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
