.TH "src/utils/Logging.h" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/Logging.h
.SH SYNOPSIS
.br
.PP
\fC#include <mutex>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBWorldArchitect::_MESSAGE\fP"
.br
.RI "Struct to order messages for a \fBLogger\fP so that order is preserved\&. "
.ti -1c
.RI "class \fBWorldArchitect::Logger\fP"
.br
.RI "Each \fBLogger\fP writes it's contents to a specific file\&. Works asynchronously\&. "
.ti -1c
.RI "class \fBWorldArchitect::LogManager\fP"
.br
.RI "Used to manage Loggers\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBWorldArchitect\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBWorldArchitect::_MESSAGE\fP \fBWorldArchitect::Message\fP"
.br
.RI "Struct to order messages for a \fBLogger\fP so that order is preserved\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBWorldArchitect::LogType\fP { \fBWorldArchitect::Error\fP, \fBWorldArchitect::MapCreation\fP }"
.br
.RI "This enum lists the different types of Loggers\&. Used for lookup of Loggers when requested with getLogger\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
