.TH "src/main.c" 3 "Wed Jan 16 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'lib/qdbmp/qdbmp\&.h'\fP
.br
\fC#include 'MapGenSystem/GridMapGenerator\&.h'\fP
.br
\fC#include 'utils/Logging\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBgetCmdOption\fP (char **begin, char **end, const string &option)"
.br
.ti -1c
.RI "bool \fBcmdOptionExists\fP (char **begin, char **end, const string &option)"
.br
.ti -1c
.RI "void \fBprintOpts\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool cmdOptionExists (char ** begin, char ** end, const string & option)"

.PP
Definition at line 21 of file main\&.c\&.
.SS "char* getCmdOption (char ** begin, char ** end, const string & option)"

.PP
Definition at line 11 of file main\&.c\&.
.SS "int main (int argc, char * argv[])"
This is the main function\&. Currently used to manually render image of map generated with the MapGenerator selected\&. This functionality will be moved to Graphics later (probably)\&. 
.PP
Definition at line 41 of file main\&.c\&.
.SS "void printOpts ()"

.PP
Definition at line 26 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
