.TH "Map" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map \- This is a virtual class for extension for different \fBMap\fP Generation methods\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.h>\fP
.SH "Detailed Description"
.PP 
This is a virtual class for extension for different \fBMap\fP Generation methods\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
