.TH "src/MapGen/MapGenerator.c" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MapGen/MapGenerator.c
.SH SYNOPSIS
.br
.PP
\fC#include 'MapGenerator\&.h'\fP
.br
\fC#include 'GridMapGenerator\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBWorldArchitect\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "MapGenerator * \fBWorldArchitect::getMapGenerator\fP (Method method)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
