.TH "md_src__r_e_a_d_m_e" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src__r_e_a_d_m_e \- High Level Design 
This will describe the purpose of the contents of each folder in this directory\&.
.PP
.SS "Source Tree"
.PP
.IP "\(bu" 2
lib
.IP "  \(bu" 4
This folder contains code from other sources I did not write\&.
.PP

.IP "\(bu" 2
MapGenSystem
.IP "  \(bu" 4
This folder contains code relating to Maps and \fBMap\fP Generation\&.
.PP

.IP "\(bu" 2
utils
.IP "  \(bu" 4
This folder contains utilities and helpers useful in various locations which I wrote\&.
.PP

.IP "\(bu" 2
Bindings
.IP "  \(bu" 4
This folder will contain language specific binding code for languages which can be used to extend \fBWorldArchitect\fP
.PP

.IP "\(bu" 2
EventSystem
.IP "  \(bu" 4
This folder contains the code relating to Events and the Events system\&.
.PP

.IP "\(bu" 2
Graphics
.IP "  \(bu" 4
This folder contains code for exporting pictures of Maps\&. \fIThis needs overhauled\fP
.PP

.IP "\(bu" 2
TagSystem
.IP "  \(bu" 4
This folder contains code relating to Tags and the Tags system\&.
.PP

.IP "\(bu" 2
SettlementSystem
.IP "  \(bu" 4
This folder contains code relating to Settlements\&.
.PP

.PP
.PP
.SS "Notes"
.PP
Previously, there was a TerrainSystem folder and a RaceSystem folder\&. This functionality has been folded into the TagSystem\&. 
