.TH "src/MapGen/Terrain.h" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MapGen/Terrain.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Graphics/Draw\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerrain\fP"
.br
.RI "This class will be used for rendering and deciding terrain\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
