.TH "Terrain" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Terrain \- This class will be used for rendering and deciding terrain\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Terrain\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBColorMap\fP \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class will be used for rendering and deciding terrain\&. 
.PP
Definition at line 6 of file Terrain\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBColorMap\fP Terrain::color"

.PP
Definition at line 9 of file Terrain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
