.TH "WorldArchitect::Terrain" 3 "Tue Feb 5 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::Terrain
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Terrain\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Terrain\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string WorldArchitect::Terrain::name"

.PP
Definition at line 12 of file Terrain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
