.TH "WorldArchitect::GridMapGenerator" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::GridMapGenerator \- This class extends \fBMapGenerator\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GridMapGenerator\&.h>\fP
.PP
Inherits \fBWorldArchitect::MapGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridMapGenerator\fP (\fBMethod\fP method)"
.br
.ti -1c
.RI "\fBMap\fP * \fBgenerateMap\fP (int mapX, int mapY, int numContinents, float percentWater)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class extends \fBMapGenerator\fP\&. 

This class uses GridPoints as the basis for how it grows landmasses and interprets the world\&. It uses a thread per landmass to grow it concurrently\&.
.PP
This Generator is associated with two Methods, GridRandom and GridPerlin\&. 
.PP
Definition at line 27 of file GridMapGenerator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GridMapGenerator::GridMapGenerator (\fBMethod\fP method)"

.PP
Definition at line 8 of file GridMapGenerator\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMap\fP * GridMapGenerator::generateMap (int mapX, int mapY, int numContinents, float percentWater)\fC [virtual]\fP"
This function will return a completed \fBMap\fP structure\&. The program should be blind to the exact implementation used to generate this map\&. 
.PP
Implements \fBWorldArchitect::MapGenerator\fP\&.
.PP
Definition at line 220 of file GridMapGenerator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
