.TH "WorldArchitect::Event" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::Event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Event\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 5 of file Event\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
