.TH "WorldArchitect::GridPoint" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::GridPoint \- This struct is how a \fBGridMap\fP stores its data for each point internally\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GridPoint\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.ti -1c
.RI "int \fBClimateIndex\fP"
.br
.ti -1c
.RI "int \fBLandmassIndex\fP"
.br
.ti -1c
.RI "bool \fBwater\fP"
.br
.ti -1c
.RI "int \fBTerrainIndex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This struct is how a \fBGridMap\fP stores its data for each point internally\&. 
.PP
Definition at line 19 of file GridPoint\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int WorldArchitect::GridPoint::ClimateIndex"

.PP
Definition at line 23 of file GridPoint\&.h\&.
.SS "float WorldArchitect::GridPoint::height"

.PP
Definition at line 22 of file GridPoint\&.h\&.
.SS "int WorldArchitect::GridPoint::LandmassIndex"

.PP
Definition at line 24 of file GridPoint\&.h\&.
.SS "int WorldArchitect::GridPoint::TerrainIndex"

.PP
Definition at line 26 of file GridPoint\&.h\&.
.SS "bool WorldArchitect::GridPoint::water"

.PP
Definition at line 25 of file GridPoint\&.h\&.
.SS "int WorldArchitect::GridPoint::x"

.PP
Definition at line 21 of file GridPoint\&.h\&.
.SS "int WorldArchitect::GridPoint::y"

.PP
Definition at line 21 of file GridPoint\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
