.TH "WorldArchitect::Tag" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::Tag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tag\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 5 of file Tag\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
