.TH "WorldArchitect::Perlin" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::Perlin
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Perlin\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBnoise\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBnoise\fP (double x, double y, double z)"
.br
.ti -1c
.RI "double \fBoctaveNoise\fP (double x, double y)"
.br
.ti -1c
.RI "double \fBoctaveNoise\fP (double x, double y, int octaves)"
.br
.ti -1c
.RI "\fBPerlin\fP ()"
.br
.ti -1c
.RI "\fBPerlin\fP (unsigned int seed, int fidelity)"
.br
.ti -1c
.RI "\fBPerlin\fP (unsigned int seed, int fidelity, double amp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file Perlin\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Perlin::Perlin ()"

.PP
Definition at line 4 of file Perlin\&.c\&.
.SS "Perlin::Perlin (unsigned int seed, int fidelity)"

.PP
Definition at line 9 of file Perlin\&.c\&.
.SS "Perlin::Perlin (unsigned int seed, int fidelity, double amp)"

.PP
Definition at line 14 of file Perlin\&.c\&.
.SH "Member Function Documentation"
.PP 
.SS "double Perlin::noise (double x, double y)"

.PP
Definition at line 32 of file Perlin\&.c\&.
.SS "double Perlin::noise (double x, double y, double z)"

.PP
Definition at line 37 of file Perlin\&.c\&.
.SS "double Perlin::octaveNoise (double x, double y)"

.PP
Definition at line 65 of file Perlin\&.c\&.
.SS "double Perlin::octaveNoise (double x, double y, int octaves)"

.PP
Definition at line 70 of file Perlin\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
