.TH "WorldArchitect::TUI" 3 "Thu Apr 4 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::TUI
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TUI\&.h>\fP
.PP
Inherits \fBWorldArchitect::UI\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 7 of file TUI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
