.TH "WorldArchitect::Parameter< T >" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::Parameter< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parameters\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char * \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetValue\fP (T newval)"
.br
.ti -1c
.RI "T \fBgetValue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class WorldArchitect::Parameter< T >"

.PP
Definition at line 8 of file Parameters\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > char* \fBWorldArchitect::Parameter\fP< T >::getName ()\fC [inline]\fP"

.PP
Definition at line 11 of file Parameters\&.h\&.
.SS "template<typename T > T \fBWorldArchitect::Parameter\fP< T >::getValue ()\fC [inline]\fP"

.PP
Definition at line 13 of file Parameters\&.h\&.
.SS "template<typename T > void \fBWorldArchitect::Parameter\fP< T >::setValue (T newval)"


.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
