.TH "WorldArchitect::_POINT" 3 "Sat Mar 23 2019" "Version 0.0.1" "WorldArchitect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WorldArchitect::_POINT \- Pair of (x, y) with equivalence operator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vector\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fB_POINT\fP &a) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pair of (x, y) with equivalence operator\&. 
.PP
Definition at line 7 of file vector\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool WorldArchitect::_POINT::operator== (const \fB_POINT\fP & a) const\fC [inline]\fP"

.PP
Definition at line 10 of file vector\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int WorldArchitect::_POINT::x"

.PP
Definition at line 9 of file vector\&.h\&.
.SS "int WorldArchitect::_POINT::y"

.PP
Definition at line 9 of file vector\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WorldArchitect from the source code\&.
